

try{
    throw new Error("harden's error~")
} catch(e){
    console.log(e)
} finally{
    console.log("finally~~~~~~~~~")
}


